version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-network
    restart: unless-stopped
  
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: phpredisadmin
    ports:
      - "8081:80"
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_AUTH=root
      
    networks:
      - redis-network
    restart: unless-stopped
    

volumes:
  app:
  redis-data:

networks:
  redis-network:
    driver: bridge